Pin rdflib to 5.0.0 - new 6.0.0 just out today seems to cause error (mportError: cannot import name 'NTriplesParser' from 'rdflib.plugins.parsers.ntriples')